// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// imonitor is an autogenerated mock type for the imonitor type
type imonitor struct {
	mock.Mock
}

// TimeCost provides a mock function with given fields: ctx, skip
func (_m *imonitor) TimeCost(ctx context.Context, skip int) func() {
	ret := _m.Called(ctx, skip)

	var r0 func()
	if rf, ok := ret.Get(0).(func(context.Context, int) func()); ok {
		r0 = rf(ctx, skip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}

	return r0
}
